### ISSUE TITLE
doubts / questions / suggest / request

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/speech-to-text-nodejs#105]
I have Dragon Naturally speaking 12 professional installed and i create a UNIVERSAL VOICE PROFILE, i have author rights about it, this is a recent video (sorry for spanish audio)

https://youtu.be/wvVl1eeMBRo?t=117

1. What is delay, why?, broadband?
2. Is possible have this offline?
3. What is accuracy
4. Is possible add new vocabulary
5. What is maximum of record in time
.
.
.

Tnks

**Comment by johnfelipe** [comment]
![limit](https://cloud.githubusercontent.com/assets/428820/15411570/85a42542-1de6-11e6-9294-b947ab522651.png)

**Comment by nfriedly** [comment]
So, to answer these briefly,

1. There is a brief delay because you have to upload the audio over the internet, and then there is a much shorter processing time. However, I believe both are acceptably small.
  * Broadband vs narrowband refers to the audio sample rate; narrowband is 8khz (8000 samples per second), while broadband is 16khz and up. 
  * Narrowband is generally used with telephone voice recognition, browsers brovide broadband-quality audio.
2. No, this is an online-only service.
3. The accuracy is very good and continually improving
4. It is not possible to add new vocabulary today, but I will pass the request along to the team. It may be added in a future update.
5. The maximum is actually determined by file size rather than audio length. Up to 100mb may be uploaded for a single transcription. For broadband WAV audio, this is around 20 minutes. But for audio compressed with Opus or FLAC, it is considerably longer, easily several hours.

**Comment by nfriedly** [comment]
Oh, and thanks for that video - I can't comment on the quality, but it looks like Watson over the internet is faster than dragon running locally which surprised me!

**Comment by johnfelipe** [comment]
6. Is possible reproduce online final transcript, something like this:
https://app.voicebase.com/autonotes/private_detail/17519536/hash=apuaYW1qaW6WaG7FlmaTcWuPmJ2YlWZsmGjHkZluxZhmlpaUl2ebmptrl5vE?vbt=0

7. Color by speaker, if different speaker then different color

**Comment by nfriedly** [comment]
1. Yes, set `timestamps: true` in your opening JSON and it will include the start and end time of each word. You'll have to create the highlighting/illumination part, but that gives you all the data you need to do it.

2. Not currently, but as with the custom vocabulary, I'll pass the request along and it may be added in a future update.

**Comment by johnfelipe** [comment]
about hightlighting pls show me how or share me a link with example

**Comment by nfriedly** [comment]
Well, you have the link you provided that can serve as an example. There's also https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/timing-stream.js which does something similar. That's about all I've got though.
