### ISSUE TITLE
select only spanish not work in chrome

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/speech-to-text-nodejs#106]
http://181.135.63.86:3002/

In chrome:

![chrome](https://cloud.githubusercontent.com/assets/428820/15489588/90a1d62c-2126-11e6-96d6-81979aac9010.png)

in firefox is good:

![firefox](https://cloud.githubusercontent.com/assets/428820/15489592/97ce574a-2126-11e6-822e-871e3bffd3b3.png)

how solve this?

**Comment by nfriedly** [comment]
@johnfelipe This isn't the correct place to ask for help building and debugging your application. Please try https://developer.ibm.com/answers/questions/ask/?topics=watson or http://stackoverflow.com/questions/ask?tags=ibm-watson although either way you'll probably have to provide more details in order to get a helpful response.
