### ISSUE TITLE
[Speech to Text]:Not working in mobile

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/speech-to-text-nodejs#121]
Hello,
I have deployed the app in bluemix. Now the url `https://<...>.mybluemix.net` is working perfectly in laptops/desktops. It also opens the initial page in mobile but the buttons for microphone, file open dialog etc. are appearing one below another instead of side by side. Import issue is buttons are not working when pressed.
Is there any other version is created for mobile app ?
If not then please let me know how to run successfully in mobile.

**Comment by kognate** [comment]
The demo does not work in mobile safari.  There isn't a mobile version of this demo app.   

You can use the ios-sdk or the android-sdk to develop speech to text applications for mobile platforms.

**Comment by jsstylos** [comment]
Should disable record or give a warning message when on mobile

**Comment by prasanta303** [comment]
On pressing the buttons nothing happens. I am not getting any error message.

**Comment by germanattanasio** [comment]
This is a known issue and it's because safari has a URL limitation that we easily exceed with the Watson token. We will probably fix this during the rebrading

**Comment by nfriedly** [comment]
I don't think Safari supports microphone access either (on desktop or mobile - http://caniuse.com/#search=getusermedia). So, it's doubly broken. 

Regardless, I agree, we should put up some warning/error message.

**Comment by jsstylos** [comment]
@germanattanasio Says that this used to work on Chrome on iOS -- we should have tests to detect when we break compatibility.

**Comment by nfriedly** [comment]
I'm pretty sure this never worked on any iOS browser (since they're all basically just Safari + glitter on iOS). You just have to use the SDK for iOS support. 

I agree that more testing is definitely in order; but the nature of this demo makes it harder than most to test. I have a halfways decent test suite set up for the speech JS SDK (it tests almost everything in Chrome and as much as it can in Firefox), so that could be a good starting point. And, once we get this demo transitioned to using the SDK, then it will directly benefit from those tests.

**Comment by nfriedly** [comment]
Closing this, as the new demo handles things much better. For modern browsers on Android, all features work. On iOS, sample playback works and the microphone button is greyed out and provides a more clear error message when clicked.
