### ISSUE TITLE
How to use STT for half-duplex conversation

### ISSUE THREAD

**Issue by gitjps** [watson-developer-cloud/speech-to-text-nodejs#128]
We want to  use STT and TTS in conjunction in a half-duplex scenario so the audio (STT) is automatically muted when Watson (Conversation, TTS) speaks. The audio is coming from/ging to a Skype for Business client. Is that supported/possible?

**Comment by nfriedly** [comment]
Hi,

This is definitely possible, see http://speech-dialog.mybluemix.net/ for a simple (somewhat dated) example. That one just opens a new STT connection each time it's ready for speech, which may not be ideal, but the SDK does automatically buffer audio while the connection is opening, so nothing would get lost.

That example uses our Speech JS SDK ([github](https://github.com/watson-developer-cloud/speech-javascript-sdk), [npm](https://www.npmjs.com/package/watson-speech)), which is what I would recommend using if you're doing something browser-based. (This demo is currently in the process of [being updated to use the SDK, along with a couple of other updates](https://github.com/watson-developer-cloud/speech-to-text-nodejs/tree/react).)

You could probably also do something where you [unpipe](https://nodejs.org/api/stream.html#stream_readable_unpipe_destination) or otherwise mute the microphone input while keeping the WebSocket connection open. I haven't tried this, but it may provide slightly faster responses. Note that you'll need to handle automatic reconnecting in the case of disconnects then. (Bumping `inactivity_timeout` from the 30 second default will help, but there are a number of things that can cause a disconnection.)
