### ISSUE TITLE
Words being misspelled 

### ISSUE THREAD

**Issue by mimoraes** [watson-developer-cloud/speech-to-text-nodejs#169]
Almost all the time the phrases come wrong, with different words spoken. Even going over https://speech-to-text-demo.mybluemix.net/ , I'm getting misspelled words. 

Does anyone know how do I improve that? How to listen/show the output exactly the same have spoken?

**Comment by germanattanasio** [comment]
Hi Michelle, 

Can you provide more details of what you are doing? What model are you trying to use? The default models don't work very well with strong accents like in my case. What I usually do is to create a custom model.

Are you trying the demo with an audio file or your microphone? It could be that your microphone is introducing some noise into the recorded audio. I saw that happening with some laptops like the Thinkpads.

**Comment by mimoraes** [comment]
pi@Rose:~/Desktop/tjbot/recipes/conversation $ node conversation.js 
info: Hello from TJBot! My name is Rose.
You can ask me to introduce myself or tell you a joke.
Try saying, "Rose, please introduce yourself" or "Rose, who are you?"
You can also say, "Rose, tell me a joke!"
info: TJBot heard: Joe 
info: TJBot heard: tell me I don't 
info: TJBot heard: tell me a joke

**Comment by germanattanasio** [comment]
Hi, @mimoraes I think this is not a problem with this sample but the service. We have made progress with the accuracy and added new features since this issue was opened.

I would suggest you try creating customization with the words that people with use with TJBot to increase the accuracy.

I'm closing this since it's not a problem with this repository but the service
