### ISSUE TITLE
The URL query argument(s) ['X-WDC-PL-OPT-OUT'] are not allowed.

### ISSUE THREAD

**Issue by jbauer180266** [watson-developer-cloud/speech-to-text-nodejs#54]
For me this demo neither works when I build it myself nor when I try the official version hosted by you. I tried it with a Logitech USB headset [which correctly records sound in the OS and Firefox 42.0 shares it], but then I get the error from the title, but I have also tried both an .ogg file downloaded from the TTS demo (which btw works - the other demo, not using the file, same error) as well as finally using the files from the Python STT demo, which also fail with the same error. Finally, since there is "opt out" in the message I played with the option whether Watson may learn from this session. However, whether I allow it or not, this demo still breaks.

Any suggestions how to fix this?
Thanks in advance.

Best,
Joe

**Comment by germanattanasio** [comment]
We have a problem with the firefox browser (see #16). While we work on that we recommend users to use Chrome or refresh the Firefox browser every time you want to record audio with the microphone. There is a hidden feature you can use to transform into wav what you send to the service so that you can test if you are sending audio correctly.

**Comment by germanattanasio** [comment]
@jbauer180266 try to update your code with the fix I just pushed or deploy your app to bluemix again. The issue was fixed

**Comment by jbauer180266** [comment]
Thank you once again. You're a machine - at least three bugs solved in a day. Impressive.
