### ISSUE TITLE
No Logs in the Console

### ISSUE THREAD

**Issue by nheidloff** [watson-developer-cloud/speech-to-text-nodejs#73]
I ran the app locally. It works, but I only see the very first console.log in my console ('listening to port'). After this no other logs are printed out.

When I run node inspector and open the URL in Chrome, nothing comes up. Not sure whether that's related to the first problem.

Is it just me? Any idea how to fix this? I looked briefly in the code but couldn't find where the logs could have been turned off. Maybe in one of the dependencies? Both issues make it really hard to extend the app.

**Comment by nfriedly** [comment]
Hi @nheidloff, this is by design. This app is built on top of Express 4 which does not include any built-in logging and we chose not to add one in order to keep the amount of code to a minimum.

However, if you would like more logging, such as an entry for each http request, it should be easy to add one. There are lots of options, but Morgan is one good choice: https://www.npmjs.com/package/morgan

To use Morgan with default settings, first install it with the command `npm install --save morgan` and then add the `require` and `app.use` lines to `config/express.js` like so:

```js
/...
var express    = require('express'),
  bodyParser   = require('body-parser');
var morgan = require('morgan'); // << added

module.exports = function (app) {
  app.set('view engine', 'ejs');
  app.enable('trust proxy');

  // Only loaded when SECURE_EXPRESS is `true`
  if (process.env.SECURE_EXPRESS)
    require('./security')(app);

  // Configure Express
  app.use(morgan('combined')); // << added
  app.use(bodyParser.urlencoded({ extended: true, limit: '1mb' }));
  app.use(bodyParser.json({ limit: '1mb' }));
  app.use(express.static(__dirname + '/../public'));
};
```

**Comment by nfriedly** [comment]
Oh, and the node inspector is probably a different issue. I've personally never been able to get node inspector to work with any app. (I haven't tried *that* hard, but I think it's safe to say that the issue is in node inspector and not this app.)
